service: tennis-whisp 

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-websockets-plugin

functions:
  connectionHandler:
    handler: src/websockets/connectionHandler.connectionHandler
    events:
      - websocket:
        routeKey: $connect
      - websocket:
        routeKey: $disconnect
  defaultHandler:
    handler: src/websockets/defaultHandler.defaultHandler
    events:
      - websocket:
          routeKey: $default
    

resources:
  Resources:
    ChatTable:
      Type: "AWS::RDS::DBInstance"
      Properties:
        AttributeDefinitions:
          - AttributeName: "connection_id"
            AttributeType: "S"
        TableName: chat
        Engine: mysql
      
