service: tennis-whisperers 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

plugins:
  - serverless-websockets-plugin

functions:
  connectionHandler:
    handler: src/websockets/connectionHandler.connectionHandler
    events:
      - websocket:
        routeKey: $connect
      - websocket:
        routeKey: $disconnect
  defaultHandler:
    handler: src/websockets/defaultHandler.defaultHandler
    events:
      - websocket:
          routeKey: $default
  sendMessageHandler:
    handler: sendMessageHandler.sendMessageHandler
    events:
      - websocket:
          routeKey: sendMessage
    

#resources:
#  Resources:
#    RDSInstance:
#      Type: "AWS::RDS::DBInstance"
#      Properties:
#        AttributeDefinitions:
#          - AttributeName: "connection_id"
#            AttributeType: "S"
#        TableName: chat
#        Engine: mysql
      
