service: tennis-whisperers 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

#  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - "execute-api:ManageConnections"
#      Resource:
#        - "arn:aws:execute-api:*:*:**/@connections/*"

#plugins:
#  - serverless-websockets-plugin

functions:
  connectionHandler:
    handler: src/websockets/connectionHandler.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: src/websockets/defaultHandler.defaultHandler
    events:
      - websocket:
          route: $default
  tournaments:
    handler: src/lambdas/tournaments.getTournaments
    timeout: 5
  players:
    handler: src/lambdas/players.getPlayers
    timeout: 5
  tournDraws:
    handler: src/lambdas/tournDraws.tournamentDraws
    timeout: 5
  tournEvents:
    handler: src/lambdas/tournEvents.tournamentEvents
    timeout: 5
  tournResults:
    handler: src/lambdas/tournResults.getResults
    timeout: 5
    

#resources:
# Resources:
#    RDSInstance:
#      Type: "AWS::RDS::DBInstance"
#      Properties:
#        AttributeDefinitions:
#          - AttributeName: "connection_id"
#            AttributeType: "S"
#        TableName: chat
#       Engine: mysql
      
